"use client";
import { useState, useEffect, useRef } from "react";
import AppShell from "@/components/layout/AppShell";
import Modal from "@/components/ui/Modal";
import { api, getStoredUser } from "@/lib/client-fetch";
import { formatSize } from "@/lib/file-utils";
import type { DiskRecord } from "@/types";

export default function DisksPage() {
  const [disks,   setDisks]   = useState<DiskRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [showImport, setShowImport] = useState(false);
  const role = getStoredUser()?.role;

  async function load() {
    setLoading(true);
    try { setDisks(await api.get<DiskRecord[]>("/api/disks")); }
    finally { setLoading(false); }
  }

  useEffect(() => { load(); }, []);

  async function deleteDisk(id: number, label: string) {
    if (!confirm(`Delete index for "${label}"?\n\nOriginal files on disk are NOT affected.`)) return;
    await api.delete(`/api/disks/${id}`);
    await load();
  }

  return (
    <AppShell>
      <div className="h-full overflow-y-auto p-8">
        <div className="max-w-4xl mx-auto">

          <div className="flex items-center justify-between mb-6">
            <div>
              <h1 className="font-display text-xl font-bold text-ink">Indexed Disks</h1>
              <p className="text-xs text-muted mt-1">Import JSON index files generated by <code className="text-blue">disk-indexer.py</code></p>
            </div>
            <button onClick={() => setShowImport(true)} className="btn-primary flex items-center gap-2">
              ⚡ Import Index
            </button>
          </div>

          {loading ? (
            <div className="text-center py-16 text-muted text-sm">Loading…</div>
          ) : disks.length === 0 ? (
            <div className="text-center py-16 text-muted">
              <div className="text-4xl mb-4">💾</div>
              <p className="text-sm">No disks indexed yet.</p>
              <p className="text-xs mt-2">Click <strong className="text-accent">⚡ Import Index</strong> to get started.</p>
            </div>
          ) : (
            <div className="space-y-2">
              {disks.map((d) => (
                <div key={d.id} className="card px-5 py-4 flex items-center gap-4 hover:border-accent/30 transition-colors">
                  <div className="w-10 h-10 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent text-lg shrink-0">💾</div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-semibold text-sm text-ink">{d.label}</span>
                      <span className="text-[10px] text-muted border border-border rounded px-1.5 py-0.5">{d.indexed_at ?? "—"}</span>
                    </div>
                    <div className="text-xs text-muted mt-0.5 truncate">{d.disk_path ?? ""}</div>
                    <div className="flex items-center gap-3 mt-1 text-[10px] text-muted flex-wrap">
                      <span>📄 {d.total_files.toLocaleString()} files</span>
                      <span>💽 {d.total_size_gb} GB</span>
                      {d.archive_file_count > 0 && <span>📦 {d.archive_file_count.toLocaleString()} in archives</span>}
                      <span className="ml-auto">Imported by <strong className="text-ink">{d.imported_by ?? "—"}</strong></span>
                    </div>
                  </div>
                  {role === "admin" && (
                    <button onClick={() => deleteDisk(d.id, d.label)} className="btn-danger shrink-0">Delete</button>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {showImport && <ImportModal onClose={() => { setShowImport(false); load(); }} />}
    </AppShell>
  );
}

// ── Import modal ───────────────────────────────────────────────────────────────
function ImportModal({ onClose }: { onClose: () => void }) {
  const [status,   setStatus]   = useState<{ msg: string; ok?: boolean } | null>(null);
  const [dragging, setDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);

  async function handleFile(file: File) {
    if (!file.name.endsWith(".json")) { setStatus({ msg: "Only .json files are supported", ok: false }); return; }
    setStatus({ msg: `Reading ${file.name}…` });
    let data: unknown;
    try { data = JSON.parse(await file.text()); }
    catch (e: any) { setStatus({ msg: `Invalid JSON: ${e.message}`, ok: false }); return; }

    setStatus({ msg: "Uploading to database…" });
    try {
      const res: any = await api.post("/api/disks", data);
      setStatus({ msg: `✓ Imported ${res.files_imported.toLocaleString()} files`, ok: true });
      setTimeout(onClose, 1500);
    } catch (e: any) {
      setStatus({ msg: `Import failed: ${e.message}`, ok: false });
    }
  }

  return (
    <Modal title="Import Index File" onClose={onClose}>
      <p className="text-xs text-muted mb-4">
        Select a <code className="text-blue">.json</code> file generated by <code className="text-blue">disk-indexer.py</code>
      </p>
      <div
        onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
        onDragLeave={() => setDragging(false)}
        onDrop={(e) => { e.preventDefault(); setDragging(false); const f = e.dataTransfer.files[0]; if (f) handleFile(f); }}
        onClick={() => inputRef.current?.click()}
        className={`border-2 border-dashed rounded-xl py-10 px-6 text-center cursor-pointer transition-all text-muted text-xs
          ${dragging ? "border-accent bg-accent/5 text-accent" : "border-border hover:border-accent hover:bg-accent/3"}`}
      >
        <div className="text-3xl mb-3">📂</div>
        Drop <code>.json</code> index file here<br />or click to browse
      </div>
      <input ref={inputRef} type="file" accept=".json" className="hidden"
        onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFile(f); }} />

      {status && (
        <p className={`mt-4 text-xs ${status.ok === true ? "text-green" : status.ok === false ? "text-danger" : "text-muted"}`}>
          {status.msg}
        </p>
      )}

      <div className="flex justify-end mt-5">
        <button onClick={onClose} className="btn-ghost">Cancel</button>
      </div>
    </Modal>
  );
}
