"use client";
import { useState, useEffect, useRef } from "react";
import AppShell from "@/components/layout/AppShell";
import Modal from "@/components/ui/Modal";
import { getToken, getStoredUser } from "@/lib/client-fetch";
import { formatSize } from "@/lib/file-utils";
import type { DiskRecord } from "@/types";

// ── helpers ────────────────────────────────────────────────────────────────────

async function apiFetch<T>(url: string, options: RequestInit = {}): Promise<T> {
  const token = getToken();
  const res = await fetch(url, {
    ...options,
    headers: {
      ...(options.headers as Record<string, string>),
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
    },
  });
  if (!res.ok) {
    const body = await res.json().catch(() => ({}));
    throw new Error(body?.detail ?? body?.error ?? `HTTP ${res.status}`);
  }
  return res.json();
}

function fmtPct(n: number) { return `${(n * 100).toFixed(1)}%`; }

// ── Disks page ─────────────────────────────────────────────────────────────────

export default function DisksPage() {
  const [disks, setDisks] = useState<DiskRecord[]>([]);
  const [loading, setLoading] = useState(true);
  const [showImport, setShowImport] = useState(false);
  const role = getStoredUser()?.role;

  async function load() {
    setLoading(true);
    try { setDisks(await apiFetch<DiskRecord[]>("/api/disks")); }
    finally { setLoading(false); }
  }

  useEffect(() => { load(); }, []);

  async function deleteDisk(id: number, label: string) {
    if (!confirm(`Delete index for "${label}"?\n\nOriginal files on disk are NOT affected.`)) return;
    const token = getToken();
    await fetch(`/api/disks/${id}`, { method: "DELETE", headers: token ? { Authorization: `Bearer ${token}` } : {} });
    await load();
  }

  return (
    <AppShell>
      <div className="h-full overflow-y-auto p-8">
        <div className="max-w-4xl mx-auto">

          <div className="flex items-center justify-between mb-6">
            <div>
              <h1 className="font-display text-xl font-bold text-ink">Indexed Disks</h1>
              <p className="text-xs text-muted mt-1">
                Import <code className="text-blue">.json</code> or{" "}
                <code className="text-blue">.json.gz</code> index files generated by{" "}
                <code className="text-blue">disk_indexer.py</code>
              </p>
            </div>
            <button onClick={() => setShowImport(true)} className="btn-primary flex items-center gap-2">
              ⚡ Import Index
            </button>
          </div>

          {loading ? (
            <div className="text-center py-16 text-muted text-sm">Loading…</div>
          ) : disks.length === 0 ? (
            <div className="text-center py-16 text-muted">
              <div className="text-4xl mb-4">💾</div>
              <p className="text-sm">No disks indexed yet.</p>
              <p className="text-xs mt-2">Click <strong className="text-accent">⚡ Import Index</strong> to get started.</p>
            </div>
          ) : (
            <div className="space-y-2">
              {disks.map((d) => (
                <div key={d.id} className="card px-5 py-4 flex items-center gap-4 hover:border-accent/30 transition-colors">
                  <div className="w-10 h-10 rounded-lg bg-accent/10 border border-accent/20 flex items-center justify-center text-accent text-lg shrink-0">💾</div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                      <span className="font-semibold text-sm text-ink">{d.label}</span>
                      <span className="text-[10px] text-muted border border-border rounded px-1.5 py-0.5">{d.indexed_at ?? "—"}</span>
                    </div>
                    <div className="text-xs text-muted mt-0.5 truncate">{d.disk_path ?? ""}</div>
                    <div className="flex items-center gap-3 mt-1 text-[10px] text-muted flex-wrap">
                      <span>📄 {d.total_files.toLocaleString()} files</span>
                      <span>💽 {d.total_size_gb} GB</span>
                      {d.archive_file_count > 0 && <span>📦 {d.archive_file_count.toLocaleString()} in archives</span>}
                      <span className="ml-auto">Imported by <strong className="text-ink">{d.imported_by ?? "—"}</strong></span>
                    </div>
                  </div>
                  {role === "admin" && (
                    <button onClick={() => deleteDisk(d.id, d.label)} className="btn-danger shrink-0">Delete</button>
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {showImport && <ImportModal onClose={() => { setShowImport(false); load(); }} />}
    </AppShell>
  );
}

// ── Import modal ───────────────────────────────────────────────────────────────

type Stage =
  | { phase: "idle" }
  | { phase: "reading"; name: string }
  | { phase: "compressing"; progress: number }   // 0–1
  | { phase: "uploading"; compressed: number; original: number }
  | { phase: "done"; imported: number; compressed: number; original: number }
  | { phase: "error"; msg: string };

function ImportModal({ onClose }: { onClose: () => void }) {
  const [stage, setStage] = useState<Stage>({ phase: "idle" });
  const [dragging, setDragging] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const abortRef = useRef<AbortController | null>(null);

  async function handleFile(file: File) {
    const isGz = file.name.endsWith(".gz");
    const isJson = file.name.endsWith(".json");
    if (!isJson && !isGz) {
      setStage({ phase: "error", msg: "Only .json or .json.gz files are supported" });
      return;
    }

    abortRef.current = new AbortController();

    // ── Step 1: read file ──────────────────────────────────────────────────
    setStage({ phase: "reading", name: file.name });
    let rawBytes: Uint8Array;
    try {
      rawBytes = new Uint8Array(await file.arrayBuffer());
    } catch (e: unknown) {
      setStage({ phase: "error", msg: `Could not read file: ${e instanceof Error ? e.message : String(e)}` });
      return;
    }

    const originalSize = rawBytes.byteLength;
    let uploadBytes = rawBytes;
    let useGzip = false;

    // ── Step 2: compress if not already gzipped ────────────────────────────
    // Only compress if the browser supports CompressionStream (all modern browsers do).
    // Skip if already .gz — user pre-compressed with disk_indexer.py --compress.
    if (!isGz && typeof CompressionStream !== "undefined") {
      setStage({ phase: "compressing", progress: 0 });
      try {
        // CompressionStream is streaming — we feed in chunks to show progress
        const cs = new CompressionStream("gzip");
        const writer = cs.writable.getWriter();
        const reader = cs.readable.getReader();

        const CHUNK = 1024 * 1024; // 1 MB chunks
        const chunks: Uint8Array[] = [];

        // Write input in chunks
        const writeAll = async () => {
          let offset = 0;
          while (offset < rawBytes.length) {
            const slice = rawBytes.slice(offset, offset + CHUNK);
            await writer.write(slice);
            offset += slice.length;
            setStage({ phase: "compressing", progress: offset / rawBytes.length });
          }
          await writer.close();
        };

        // Read compressed output
        const readAll = async () => {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            chunks.push(value);
          }
        };

        await Promise.all([writeAll(), readAll()]);

        const totalLen = chunks.reduce((s, c) => s + c.length, 0);
        const compressed = new Uint8Array(totalLen);
        let pos = 0;
        for (const c of chunks) { compressed.set(c, pos); pos += c.length; }

        uploadBytes = compressed;
        useGzip = true;
      } catch {
        // Compression failed — fall back to uncompressed upload
        uploadBytes = rawBytes;
        useGzip = false;
      }
    } else if (isGz) {
      useGzip = true;
    }

    // ── Step 3: upload ─────────────────────────────────────────────────────
    setStage({ phase: "uploading", compressed: uploadBytes.byteLength, original: originalSize });

    const token = getToken();
    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...(useGzip ? { "Content-Encoding": "gzip" } : {}),
    };

    try {
      const res = await fetch("/api/disks", {
        method: "POST",
        headers,
        body: uploadBytes.buffer as ArrayBuffer,
        signal: abortRef.current.signal,
      });

      const data = await res.json();

      if (!res.ok) {
        const detail = data?.detail ?? data?.error ?? `HTTP ${res.status}`;
        // Show validation issues if present
        const issueList: string = Array.isArray(data?.issues)
          ? "\n" + data.issues.slice(0, 5).map((i: any) => `  • ${i.path}: ${i.message}`).join("\n")
          : "";
        setStage({ phase: "error", msg: detail + issueList });
        return;
      }

      setStage({
        phase: "done",
        imported: data.files_imported,
        compressed: uploadBytes.byteLength,
        original: originalSize,
      });
      setTimeout(onClose, 2500);

    } catch (e: unknown) {
      if ((e as any)?.name === "AbortError") return;
      setStage({ phase: "error", msg: e instanceof Error ? e.message : String(e) });
    }
  }

  function cancel() {
    abortRef.current?.abort();
    onClose();
  }

  return (
    <Modal title="Import Index File" onClose={cancel}>
      <p className="text-xs text-muted mb-4">
        Accepts <code className="text-blue">.json</code> or pre-compressed{" "}
        <code className="text-blue">.json.gz</code> — plain JSON is compressed
        automatically in the browser before upload.
      </p>

      {/* Drop zone — only shown when idle or after error */}
      {(stage.phase === "idle" || stage.phase === "error") && (
        <>
          <div
            onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
            onDragLeave={() => setDragging(false)}
            onDrop={(e) => {
              e.preventDefault(); setDragging(false);
              const f = e.dataTransfer.files[0];
              if (f) handleFile(f);
            }}
            onClick={() => inputRef.current?.click()}
            className={`border-2 border-dashed rounded-xl py-10 px-6 text-center cursor-pointer
              transition-all text-muted text-xs
              ${dragging ? "border-accent bg-accent/5 text-accent" : "border-border hover:border-accent hover:bg-accent/3"}`}
          >
            <div className="text-3xl mb-3">📂</div>
            Drop <code>.json</code> or <code>.json.gz</code> here
            <br />or click to browse
          </div>
          <input
            ref={inputRef}
            type="file"
            accept=".json,.json.gz,.gz"
            className="hidden"
            onChange={(e) => { const f = e.target.files?.[0]; if (f) handleFile(f); }}
          />
        </>
      )}

      {/* Status area */}
      <div className="mt-4 space-y-2">
        {stage.phase === "reading" && (
          <StatusRow icon="📖" color="text-muted" msg={`Reading ${stage.name}…`} />
        )}

        {stage.phase === "compressing" && (
          <>
            <StatusRow icon="🗜️" color="text-blue" msg="Compressing…" />
            <ProgressBar value={stage.progress} color="bg-blue" />
          </>
        )}

        {stage.phase === "uploading" && (
          <>
            <StatusRow icon="⬆️" color="text-blue" msg="Uploading…" />
            <div className="text-[10px] text-muted">
              {formatSize(stage.compressed)} compressed
              {stage.compressed < stage.original && (
                <span className="text-green ml-1">
                  ({fmtPct(1 - stage.compressed / stage.original)} smaller)
                </span>
              )}
              <span className="ml-1 text-muted/60">from {formatSize(stage.original)} original</span>
            </div>
            <ProgressBar value={null} color="bg-blue" />
          </>
        )}

        {stage.phase === "done" && (
          <>
            <StatusRow icon="✓" color="text-green"
              msg={`Imported ${stage.imported.toLocaleString()} files`} />
            <div className="text-[10px] text-muted">
              Uploaded {formatSize(stage.compressed)}
              {stage.compressed < stage.original && (
                <span className="text-green ml-1">
                  · saved {formatSize(stage.original - stage.compressed)}{" "}
                  ({fmtPct(1 - stage.compressed / stage.original)})
                </span>
              )}
            </div>
          </>
        )}

        {stage.phase === "error" && (
          <div className="bg-danger/10 border border-danger/30 rounded-lg px-3 py-2.5">
            <p className="text-danger text-xs font-semibold mb-1">Import failed</p>
            <pre className="text-danger/80 text-[10px] whitespace-pre-wrap break-words">{stage.msg}</pre>
          </div>
        )}
      </div>

      <div className="flex justify-end mt-5">
        {stage.phase === "done" ? (
          <button onClick={onClose} className="btn-primary">Close</button>
        ) : (
          <button onClick={cancel} className="btn-ghost">
            {stage.phase === "idle" || stage.phase === "error" ? "Cancel" : "Abort"}
          </button>
        )}
      </div>
    </Modal>
  );
}

// ── Sub-components ─────────────────────────────────────────────────────────────

function StatusRow({ icon, color, msg }: { icon: string; color: string; msg: string }) {
  return (
    <div className={`flex items-center gap-2 text-xs ${color}`}>
      <span>{icon}</span>
      <span>{msg}</span>
    </div>
  );
}

function ProgressBar({ value, color }: { value: number | null; color: string }) {
  // value=null → indeterminate animation
  return (
    <div className="h-1 bg-surface2 rounded-full overflow-hidden">
      {value === null ? (
        <div className={`h-full w-1/3 ${color} opacity-70 rounded-full animate-pulse`} />
      ) : (
        <div
          className={`h-full ${color} rounded-full transition-all duration-150`}
          style={{ width: `${Math.min(value * 100, 100)}%` }}
        />
      )}
    </div>
  );
}